// Provider-side manifest: the API must be able to tell whether a symbol is
// genuinely fresh, stale, or missing. Keep this aligned with engine/signal8h/catalog.py.
export const SIGNAL_8H_EXPECTED_SYMBOLS = [
  'XAUUSD',
  'XAGUSD',
  'USOUSD',
  'XCUUSD',
  'WHEAT',
  'ASX200',
  'CAN60',
  'CN50',
  'FRA40',
  'EUSTX50',
  'HK50',
  'GER40',
  'JPN225',
  'NDQ100',
  'NTH25',
  'ITA40',
  'SWI20',
  'SPX500',
  'UK100',
  'US2000',
  'US30',
  'AUDNZD',
  'AUDCAD',
  'AUDUSD',
  'NZDCAD',
  'NZDUSD',
  'USDJPY',
  'USDCAD',
  'USDBRL',
  'EURAUD',
  'EURCAD',
  'EURGBP',
  'EURNZD',
  'EURUSD',
  'GBPAUD',
  'GBPCAD',
  'GBPNZD',
  'GBPUSD',
  'AUDJPY',
  'CADJPY',
  'CHFJPY',
  'EURJPY',
  'GBPJPY',
  'NZDJPY',
  'AUDCHF',
  'CADCHF',
  'EURCHF',
  'GBPCHF',
  'NZDCHF',
  'USDCHF',
  'XAUAUD',
  'XAUEUR',
  'XAUGBP',
  'XAUJPY',
  'XAGEUR',
  'XAGJPY',
] as const

export const SIGNAL_8H_STALE_AFTER_HOURS = 24
